# Generated by Django 3.2.7 on 2021-10-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag_line',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
